// Generated by gencpp from file openhand_node/HoldServosRequest.msg
// DO NOT EDIT!


#ifndef OPENHAND_NODE_MESSAGE_HOLDSERVOSREQUEST_H
#define OPENHAND_NODE_MESSAGE_HOLDSERVOSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openhand_node
{
template <class ContainerAllocator>
struct HoldServosRequest_
{
  typedef HoldServosRequest_<ContainerAllocator> Type;

  HoldServosRequest_()
    : offset_scale(0)  {
    }
  HoldServosRequest_(const ContainerAllocator& _alloc)
    : offset_scale(0)  {
  (void)_alloc;
    }



   typedef int32_t _offset_scale_type;
  _offset_scale_type offset_scale;





  typedef boost::shared_ptr< ::openhand_node::HoldServosRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openhand_node::HoldServosRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HoldServosRequest_

typedef ::openhand_node::HoldServosRequest_<std::allocator<void> > HoldServosRequest;

typedef boost::shared_ptr< ::openhand_node::HoldServosRequest > HoldServosRequestPtr;
typedef boost::shared_ptr< ::openhand_node::HoldServosRequest const> HoldServosRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openhand_node::HoldServosRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openhand_node::HoldServosRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openhand_node::HoldServosRequest_<ContainerAllocator1> & lhs, const ::openhand_node::HoldServosRequest_<ContainerAllocator2> & rhs)
{
  return lhs.offset_scale == rhs.offset_scale;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openhand_node::HoldServosRequest_<ContainerAllocator1> & lhs, const ::openhand_node::HoldServosRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openhand_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openhand_node::HoldServosRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openhand_node::HoldServosRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openhand_node::HoldServosRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openhand_node::HoldServosRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openhand_node::HoldServosRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openhand_node::HoldServosRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openhand_node::HoldServosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67b1f8b2dc0155309f8337c145c6af04";
  }

  static const char* value(const ::openhand_node::HoldServosRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67b1f8b2dc015530ULL;
  static const uint64_t static_value2 = 0x9f8337c145c6af04ULL;
};

template<class ContainerAllocator>
struct DataType< ::openhand_node::HoldServosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openhand_node/HoldServosRequest";
  }

  static const char* value(const ::openhand_node::HoldServosRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openhand_node::HoldServosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 offset_scale\n"
;
  }

  static const char* value(const ::openhand_node::HoldServosRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openhand_node::HoldServosRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.offset_scale);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HoldServosRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openhand_node::HoldServosRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openhand_node::HoldServosRequest_<ContainerAllocator>& v)
  {
    s << indent << "offset_scale: ";
    Printer<int32_t>::stream(s, indent + "  ", v.offset_scale);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENHAND_NODE_MESSAGE_HOLDSERVOSREQUEST_H
