// Generated by gencpp from file openhand_node/MoveServos.msg
// DO NOT EDIT!


#ifndef OPENHAND_NODE_MESSAGE_MOVESERVOS_H
#define OPENHAND_NODE_MESSAGE_MOVESERVOS_H

#include <ros/service_traits.h>


#include <openhand_node/MoveServosRequest.h>
#include <openhand_node/MoveServosResponse.h>


namespace openhand_node
{

struct MoveServos
{

typedef MoveServosRequest Request;
typedef MoveServosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveServos
} // namespace openhand_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::openhand_node::MoveServos > {
  static const char* value()
  {
    return "183031e0becb89936a926d61b84a7478";
  }

  static const char* value(const ::openhand_node::MoveServos&) { return value(); }
};

template<>
struct DataType< ::openhand_node::MoveServos > {
  static const char* value()
  {
    return "openhand_node/MoveServos";
  }

  static const char* value(const ::openhand_node::MoveServos&) { return value(); }
};


// service_traits::MD5Sum< ::openhand_node::MoveServosRequest> should match
// service_traits::MD5Sum< ::openhand_node::MoveServos >
template<>
struct MD5Sum< ::openhand_node::MoveServosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::openhand_node::MoveServos >::value();
  }
  static const char* value(const ::openhand_node::MoveServosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::openhand_node::MoveServosRequest> should match
// service_traits::DataType< ::openhand_node::MoveServos >
template<>
struct DataType< ::openhand_node::MoveServosRequest>
{
  static const char* value()
  {
    return DataType< ::openhand_node::MoveServos >::value();
  }
  static const char* value(const ::openhand_node::MoveServosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::openhand_node::MoveServosResponse> should match
// service_traits::MD5Sum< ::openhand_node::MoveServos >
template<>
struct MD5Sum< ::openhand_node::MoveServosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::openhand_node::MoveServos >::value();
  }
  static const char* value(const ::openhand_node::MoveServosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::openhand_node::MoveServosResponse> should match
// service_traits::DataType< ::openhand_node::MoveServos >
template<>
struct DataType< ::openhand_node::MoveServosResponse>
{
  static const char* value()
  {
    return DataType< ::openhand_node::MoveServos >::value();
  }
  static const char* value(const ::openhand_node::MoveServosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPENHAND_NODE_MESSAGE_MOVESERVOS_H
