// Generated by gencpp from file openhand_node/ReadServos.msg
// DO NOT EDIT!


#ifndef OPENHAND_NODE_MESSAGE_READSERVOS_H
#define OPENHAND_NODE_MESSAGE_READSERVOS_H

#include <ros/service_traits.h>


#include <openhand_node/ReadServosRequest.h>
#include <openhand_node/ReadServosResponse.h>


namespace openhand_node
{

struct ReadServos
{

typedef ReadServosRequest Request;
typedef ReadServosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReadServos
} // namespace openhand_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::openhand_node::ReadServos > {
  static const char* value()
  {
    return "662e32bfc46f37715bb1455cf7d299a9";
  }

  static const char* value(const ::openhand_node::ReadServos&) { return value(); }
};

template<>
struct DataType< ::openhand_node::ReadServos > {
  static const char* value()
  {
    return "openhand_node/ReadServos";
  }

  static const char* value(const ::openhand_node::ReadServos&) { return value(); }
};


// service_traits::MD5Sum< ::openhand_node::ReadServosRequest> should match
// service_traits::MD5Sum< ::openhand_node::ReadServos >
template<>
struct MD5Sum< ::openhand_node::ReadServosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::openhand_node::ReadServos >::value();
  }
  static const char* value(const ::openhand_node::ReadServosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::openhand_node::ReadServosRequest> should match
// service_traits::DataType< ::openhand_node::ReadServos >
template<>
struct DataType< ::openhand_node::ReadServosRequest>
{
  static const char* value()
  {
    return DataType< ::openhand_node::ReadServos >::value();
  }
  static const char* value(const ::openhand_node::ReadServosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::openhand_node::ReadServosResponse> should match
// service_traits::MD5Sum< ::openhand_node::ReadServos >
template<>
struct MD5Sum< ::openhand_node::ReadServosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::openhand_node::ReadServos >::value();
  }
  static const char* value(const ::openhand_node::ReadServosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::openhand_node::ReadServosResponse> should match
// service_traits::DataType< ::openhand_node::ReadServos >
template<>
struct DataType< ::openhand_node::ReadServosResponse>
{
  static const char* value()
  {
    return DataType< ::openhand_node::ReadServos >::value();
  }
  static const char* value(const ::openhand_node::ReadServosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPENHAND_NODE_MESSAGE_READSERVOS_H
