// Generated by gencpp from file openhand_node/ReadSensorsRequest.msg
// DO NOT EDIT!


#ifndef OPENHAND_NODE_MESSAGE_READSENSORSREQUEST_H
#define OPENHAND_NODE_MESSAGE_READSENSORSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openhand_node
{
template <class ContainerAllocator>
struct ReadSensorsRequest_
{
  typedef ReadSensorsRequest_<ContainerAllocator> Type;

  ReadSensorsRequest_()
    : num_sensors(0)  {
    }
  ReadSensorsRequest_(const ContainerAllocator& _alloc)
    : num_sensors(0)  {
  (void)_alloc;
    }



   typedef int32_t _num_sensors_type;
  _num_sensors_type num_sensors;





  typedef boost::shared_ptr< ::openhand_node::ReadSensorsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openhand_node::ReadSensorsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReadSensorsRequest_

typedef ::openhand_node::ReadSensorsRequest_<std::allocator<void> > ReadSensorsRequest;

typedef boost::shared_ptr< ::openhand_node::ReadSensorsRequest > ReadSensorsRequestPtr;
typedef boost::shared_ptr< ::openhand_node::ReadSensorsRequest const> ReadSensorsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openhand_node::ReadSensorsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openhand_node::ReadSensorsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openhand_node::ReadSensorsRequest_<ContainerAllocator1> & lhs, const ::openhand_node::ReadSensorsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num_sensors == rhs.num_sensors;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openhand_node::ReadSensorsRequest_<ContainerAllocator1> & lhs, const ::openhand_node::ReadSensorsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openhand_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openhand_node::ReadSensorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openhand_node::ReadSensorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openhand_node::ReadSensorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openhand_node::ReadSensorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openhand_node::ReadSensorsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openhand_node::ReadSensorsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openhand_node::ReadSensorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "850b23862be1565b5d9c714a58621559";
  }

  static const char* value(const ::openhand_node::ReadSensorsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x850b23862be1565bULL;
  static const uint64_t static_value2 = 0x5d9c714a58621559ULL;
};

template<class ContainerAllocator>
struct DataType< ::openhand_node::ReadSensorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openhand_node/ReadSensorsRequest";
  }

  static const char* value(const ::openhand_node::ReadSensorsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openhand_node::ReadSensorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 num_sensors\n"
;
  }

  static const char* value(const ::openhand_node::ReadSensorsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openhand_node::ReadSensorsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_sensors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadSensorsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openhand_node::ReadSensorsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openhand_node::ReadSensorsRequest_<ContainerAllocator>& v)
  {
    s << indent << "num_sensors: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_sensors);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENHAND_NODE_MESSAGE_READSENSORSREQUEST_H
