// Generated by gencpp from file openhand_node/ReadTemperature.msg
// DO NOT EDIT!


#ifndef OPENHAND_NODE_MESSAGE_READTEMPERATURE_H
#define OPENHAND_NODE_MESSAGE_READTEMPERATURE_H

#include <ros/service_traits.h>


#include <openhand_node/ReadTemperatureRequest.h>
#include <openhand_node/ReadTemperatureResponse.h>


namespace openhand_node
{

struct ReadTemperature
{

typedef ReadTemperatureRequest Request;
typedef ReadTemperatureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReadTemperature
} // namespace openhand_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::openhand_node::ReadTemperature > {
  static const char* value()
  {
    return "52444e69c3eaa80dd939a5bad6dbe319";
  }

  static const char* value(const ::openhand_node::ReadTemperature&) { return value(); }
};

template<>
struct DataType< ::openhand_node::ReadTemperature > {
  static const char* value()
  {
    return "openhand_node/ReadTemperature";
  }

  static const char* value(const ::openhand_node::ReadTemperature&) { return value(); }
};


// service_traits::MD5Sum< ::openhand_node::ReadTemperatureRequest> should match
// service_traits::MD5Sum< ::openhand_node::ReadTemperature >
template<>
struct MD5Sum< ::openhand_node::ReadTemperatureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::openhand_node::ReadTemperature >::value();
  }
  static const char* value(const ::openhand_node::ReadTemperatureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::openhand_node::ReadTemperatureRequest> should match
// service_traits::DataType< ::openhand_node::ReadTemperature >
template<>
struct DataType< ::openhand_node::ReadTemperatureRequest>
{
  static const char* value()
  {
    return DataType< ::openhand_node::ReadTemperature >::value();
  }
  static const char* value(const ::openhand_node::ReadTemperatureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::openhand_node::ReadTemperatureResponse> should match
// service_traits::MD5Sum< ::openhand_node::ReadTemperature >
template<>
struct MD5Sum< ::openhand_node::ReadTemperatureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::openhand_node::ReadTemperature >::value();
  }
  static const char* value(const ::openhand_node::ReadTemperatureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::openhand_node::ReadTemperatureResponse> should match
// service_traits::DataType< ::openhand_node::ReadTemperature >
template<>
struct DataType< ::openhand_node::ReadTemperatureResponse>
{
  static const char* value()
  {
    return DataType< ::openhand_node::ReadTemperature >::value();
  }
  static const char* value(const ::openhand_node::ReadTemperatureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPENHAND_NODE_MESSAGE_READTEMPERATURE_H
