// Generated by gencpp from file openhand_node/ReadLoad.msg
// DO NOT EDIT!


#ifndef OPENHAND_NODE_MESSAGE_READLOAD_H
#define OPENHAND_NODE_MESSAGE_READLOAD_H

#include <ros/service_traits.h>


#include <openhand_node/ReadLoadRequest.h>
#include <openhand_node/ReadLoadResponse.h>


namespace openhand_node
{

struct ReadLoad
{

typedef ReadLoadRequest Request;
typedef ReadLoadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReadLoad
} // namespace openhand_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::openhand_node::ReadLoad > {
  static const char* value()
  {
    return "484bc5de2725aa512e1b0578d3e540c4";
  }

  static const char* value(const ::openhand_node::ReadLoad&) { return value(); }
};

template<>
struct DataType< ::openhand_node::ReadLoad > {
  static const char* value()
  {
    return "openhand_node/ReadLoad";
  }

  static const char* value(const ::openhand_node::ReadLoad&) { return value(); }
};


// service_traits::MD5Sum< ::openhand_node::ReadLoadRequest> should match
// service_traits::MD5Sum< ::openhand_node::ReadLoad >
template<>
struct MD5Sum< ::openhand_node::ReadLoadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::openhand_node::ReadLoad >::value();
  }
  static const char* value(const ::openhand_node::ReadLoadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::openhand_node::ReadLoadRequest> should match
// service_traits::DataType< ::openhand_node::ReadLoad >
template<>
struct DataType< ::openhand_node::ReadLoadRequest>
{
  static const char* value()
  {
    return DataType< ::openhand_node::ReadLoad >::value();
  }
  static const char* value(const ::openhand_node::ReadLoadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::openhand_node::ReadLoadResponse> should match
// service_traits::MD5Sum< ::openhand_node::ReadLoad >
template<>
struct MD5Sum< ::openhand_node::ReadLoadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::openhand_node::ReadLoad >::value();
  }
  static const char* value(const ::openhand_node::ReadLoadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::openhand_node::ReadLoadResponse> should match
// service_traits::DataType< ::openhand_node::ReadLoad >
template<>
struct DataType< ::openhand_node::ReadLoadResponse>
{
  static const char* value()
  {
    return DataType< ::openhand_node::ReadLoad >::value();
  }
  static const char* value(const ::openhand_node::ReadLoadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPENHAND_NODE_MESSAGE_READLOAD_H
