// Generated by gencpp from file openhand_node/ReadLoadResponse.msg
// DO NOT EDIT!


#ifndef OPENHAND_NODE_MESSAGE_READLOADRESPONSE_H
#define OPENHAND_NODE_MESSAGE_READLOADRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openhand_node
{
template <class ContainerAllocator>
struct ReadLoadResponse_
{
  typedef ReadLoadResponse_<ContainerAllocator> Type;

  ReadLoadResponse_()
    : load()  {
    }
  ReadLoadResponse_(const ContainerAllocator& _alloc)
    : load(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _load_type;
  _load_type load;





  typedef boost::shared_ptr< ::openhand_node::ReadLoadResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openhand_node::ReadLoadResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReadLoadResponse_

typedef ::openhand_node::ReadLoadResponse_<std::allocator<void> > ReadLoadResponse;

typedef boost::shared_ptr< ::openhand_node::ReadLoadResponse > ReadLoadResponsePtr;
typedef boost::shared_ptr< ::openhand_node::ReadLoadResponse const> ReadLoadResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openhand_node::ReadLoadResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openhand_node::ReadLoadResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openhand_node::ReadLoadResponse_<ContainerAllocator1> & lhs, const ::openhand_node::ReadLoadResponse_<ContainerAllocator2> & rhs)
{
  return lhs.load == rhs.load;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openhand_node::ReadLoadResponse_<ContainerAllocator1> & lhs, const ::openhand_node::ReadLoadResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openhand_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openhand_node::ReadLoadResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openhand_node::ReadLoadResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openhand_node::ReadLoadResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openhand_node::ReadLoadResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openhand_node::ReadLoadResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openhand_node::ReadLoadResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openhand_node::ReadLoadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "484bc5de2725aa512e1b0578d3e540c4";
  }

  static const char* value(const ::openhand_node::ReadLoadResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x484bc5de2725aa51ULL;
  static const uint64_t static_value2 = 0x2e1b0578d3e540c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::openhand_node::ReadLoadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openhand_node/ReadLoadResponse";
  }

  static const char* value(const ::openhand_node::ReadLoadResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openhand_node::ReadLoadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] load\n"
"\n"
;
  }

  static const char* value(const ::openhand_node::ReadLoadResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openhand_node::ReadLoadResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.load);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadLoadResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openhand_node::ReadLoadResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openhand_node::ReadLoadResponse_<ContainerAllocator>& v)
  {
    s << indent << "load[]" << std::endl;
    for (size_t i = 0; i < v.load.size(); ++i)
    {
      s << indent << "  load[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.load[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENHAND_NODE_MESSAGE_READLOADRESPONSE_H
