// Generated by gencpp from file openhand_node/TorqueServos.msg
// DO NOT EDIT!


#ifndef OPENHAND_NODE_MESSAGE_TORQUESERVOS_H
#define OPENHAND_NODE_MESSAGE_TORQUESERVOS_H

#include <ros/service_traits.h>


#include <openhand_node/TorqueServosRequest.h>
#include <openhand_node/TorqueServosResponse.h>


namespace openhand_node
{

struct TorqueServos
{

typedef TorqueServosRequest Request;
typedef TorqueServosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TorqueServos
} // namespace openhand_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::openhand_node::TorqueServos > {
  static const char* value()
  {
    return "5ef27f5b23c316f62d99934009982e26";
  }

  static const char* value(const ::openhand_node::TorqueServos&) { return value(); }
};

template<>
struct DataType< ::openhand_node::TorqueServos > {
  static const char* value()
  {
    return "openhand_node/TorqueServos";
  }

  static const char* value(const ::openhand_node::TorqueServos&) { return value(); }
};


// service_traits::MD5Sum< ::openhand_node::TorqueServosRequest> should match
// service_traits::MD5Sum< ::openhand_node::TorqueServos >
template<>
struct MD5Sum< ::openhand_node::TorqueServosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::openhand_node::TorqueServos >::value();
  }
  static const char* value(const ::openhand_node::TorqueServosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::openhand_node::TorqueServosRequest> should match
// service_traits::DataType< ::openhand_node::TorqueServos >
template<>
struct DataType< ::openhand_node::TorqueServosRequest>
{
  static const char* value()
  {
    return DataType< ::openhand_node::TorqueServos >::value();
  }
  static const char* value(const ::openhand_node::TorqueServosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::openhand_node::TorqueServosResponse> should match
// service_traits::MD5Sum< ::openhand_node::TorqueServos >
template<>
struct MD5Sum< ::openhand_node::TorqueServosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::openhand_node::TorqueServos >::value();
  }
  static const char* value(const ::openhand_node::TorqueServosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::openhand_node::TorqueServosResponse> should match
// service_traits::DataType< ::openhand_node::TorqueServos >
template<>
struct DataType< ::openhand_node::TorqueServosResponse>
{
  static const char* value()
  {
    return DataType< ::openhand_node::TorqueServos >::value();
  }
  static const char* value(const ::openhand_node::TorqueServosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPENHAND_NODE_MESSAGE_TORQUESERVOS_H
