// Generated by gencpp from file openhand_node/TorqueServosResponse.msg
// DO NOT EDIT!


#ifndef OPENHAND_NODE_MESSAGE_TORQUESERVOSRESPONSE_H
#define OPENHAND_NODE_MESSAGE_TORQUESERVOSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openhand_node
{
template <class ContainerAllocator>
struct TorqueServosResponse_
{
  typedef TorqueServosResponse_<ContainerAllocator> Type;

  TorqueServosResponse_()
    : err(0)  {
    }
  TorqueServosResponse_(const ContainerAllocator& _alloc)
    : err(0)  {
  (void)_alloc;
    }



   typedef int32_t _err_type;
  _err_type err;





  typedef boost::shared_ptr< ::openhand_node::TorqueServosResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openhand_node::TorqueServosResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TorqueServosResponse_

typedef ::openhand_node::TorqueServosResponse_<std::allocator<void> > TorqueServosResponse;

typedef boost::shared_ptr< ::openhand_node::TorqueServosResponse > TorqueServosResponsePtr;
typedef boost::shared_ptr< ::openhand_node::TorqueServosResponse const> TorqueServosResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openhand_node::TorqueServosResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openhand_node::TorqueServosResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openhand_node::TorqueServosResponse_<ContainerAllocator1> & lhs, const ::openhand_node::TorqueServosResponse_<ContainerAllocator2> & rhs)
{
  return lhs.err == rhs.err;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openhand_node::TorqueServosResponse_<ContainerAllocator1> & lhs, const ::openhand_node::TorqueServosResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openhand_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openhand_node::TorqueServosResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openhand_node::TorqueServosResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openhand_node::TorqueServosResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openhand_node::TorqueServosResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openhand_node::TorqueServosResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openhand_node::TorqueServosResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openhand_node::TorqueServosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6e094011a4dfaee5eddf447220446cf";
  }

  static const char* value(const ::openhand_node::TorqueServosResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6e094011a4dfaeeULL;
  static const uint64_t static_value2 = 0x5eddf447220446cfULL;
};

template<class ContainerAllocator>
struct DataType< ::openhand_node::TorqueServosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openhand_node/TorqueServosResponse";
  }

  static const char* value(const ::openhand_node::TorqueServosResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openhand_node::TorqueServosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 err\n"
"\n"
;
  }

  static const char* value(const ::openhand_node::TorqueServosResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openhand_node::TorqueServosResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.err);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TorqueServosResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openhand_node::TorqueServosResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openhand_node::TorqueServosResponse_<ContainerAllocator>& v)
  {
    s << indent << "err: ";
    Printer<int32_t>::stream(s, indent + "  ", v.err);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENHAND_NODE_MESSAGE_TORQUESERVOSRESPONSE_H
