// Generated by gencpp from file openhand_node/TorqueServosRequest.msg
// DO NOT EDIT!


#ifndef OPENHAND_NODE_MESSAGE_TORQUESERVOSREQUEST_H
#define OPENHAND_NODE_MESSAGE_TORQUESERVOSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openhand_node
{
template <class ContainerAllocator>
struct TorqueServosRequest_
{
  typedef TorqueServosRequest_<ContainerAllocator> Type;

  TorqueServosRequest_()
    : servo_indices()
    , torq()  {
    }
  TorqueServosRequest_(const ContainerAllocator& _alloc)
    : servo_indices(_alloc)
    , torq(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _servo_indices_type;
  _servo_indices_type servo_indices;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _torq_type;
  _torq_type torq;





  typedef boost::shared_ptr< ::openhand_node::TorqueServosRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openhand_node::TorqueServosRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TorqueServosRequest_

typedef ::openhand_node::TorqueServosRequest_<std::allocator<void> > TorqueServosRequest;

typedef boost::shared_ptr< ::openhand_node::TorqueServosRequest > TorqueServosRequestPtr;
typedef boost::shared_ptr< ::openhand_node::TorqueServosRequest const> TorqueServosRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openhand_node::TorqueServosRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openhand_node::TorqueServosRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openhand_node::TorqueServosRequest_<ContainerAllocator1> & lhs, const ::openhand_node::TorqueServosRequest_<ContainerAllocator2> & rhs)
{
  return lhs.servo_indices == rhs.servo_indices &&
    lhs.torq == rhs.torq;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openhand_node::TorqueServosRequest_<ContainerAllocator1> & lhs, const ::openhand_node::TorqueServosRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openhand_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openhand_node::TorqueServosRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openhand_node::TorqueServosRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openhand_node::TorqueServosRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openhand_node::TorqueServosRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openhand_node::TorqueServosRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openhand_node::TorqueServosRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openhand_node::TorqueServosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "895086b4bd1390acd626a0b659916644";
  }

  static const char* value(const ::openhand_node::TorqueServosRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x895086b4bd1390acULL;
  static const uint64_t static_value2 = 0xd626a0b659916644ULL;
};

template<class ContainerAllocator>
struct DataType< ::openhand_node::TorqueServosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openhand_node/TorqueServosRequest";
  }

  static const char* value(const ::openhand_node::TorqueServosRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openhand_node::TorqueServosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] servo_indices\n"
"float32[] torq\n"
;
  }

  static const char* value(const ::openhand_node::TorqueServosRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openhand_node::TorqueServosRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servo_indices);
      stream.next(m.torq);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TorqueServosRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openhand_node::TorqueServosRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openhand_node::TorqueServosRequest_<ContainerAllocator>& v)
  {
    s << indent << "servo_indices[]" << std::endl;
    for (size_t i = 0; i < v.servo_indices.size(); ++i)
    {
      s << indent << "  servo_indices[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.servo_indices[i]);
    }
    s << indent << "torq[]" << std::endl;
    for (size_t i = 0; i < v.torq.size(); ++i)
    {
      s << indent << "  torq[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.torq[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENHAND_NODE_MESSAGE_TORQUESERVOSREQUEST_H
