// Generated by gencpp from file rollout/IsDroppedRequest.msg
// DO NOT EDIT!


#ifndef ROLLOUT_MESSAGE_ISDROPPEDREQUEST_H
#define ROLLOUT_MESSAGE_ISDROPPEDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rollout
{
template <class ContainerAllocator>
struct IsDroppedRequest_
{
  typedef IsDroppedRequest_<ContainerAllocator> Type;

  IsDroppedRequest_()
    {
    }
  IsDroppedRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rollout::IsDroppedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rollout::IsDroppedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IsDroppedRequest_

typedef ::rollout::IsDroppedRequest_<std::allocator<void> > IsDroppedRequest;

typedef boost::shared_ptr< ::rollout::IsDroppedRequest > IsDroppedRequestPtr;
typedef boost::shared_ptr< ::rollout::IsDroppedRequest const> IsDroppedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rollout::IsDroppedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rollout::IsDroppedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace rollout

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rollout::IsDroppedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rollout::IsDroppedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rollout::IsDroppedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rollout::IsDroppedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rollout::IsDroppedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rollout::IsDroppedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rollout::IsDroppedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rollout::IsDroppedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rollout::IsDroppedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rollout/IsDroppedRequest";
  }

  static const char* value(const ::rollout::IsDroppedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rollout::IsDroppedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::rollout::IsDroppedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rollout::IsDroppedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IsDroppedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rollout::IsDroppedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rollout::IsDroppedRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROLLOUT_MESSAGE_ISDROPPEDREQUEST_H
