// Generated by gencpp from file rollout/MoveServosRequest.msg
// DO NOT EDIT!


#ifndef ROLLOUT_MESSAGE_MOVESERVOSREQUEST_H
#define ROLLOUT_MESSAGE_MOVESERVOSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rollout
{
template <class ContainerAllocator>
struct MoveServosRequest_
{
  typedef MoveServosRequest_<ContainerAllocator> Type;

  MoveServosRequest_()
    : pos()  {
    }
  MoveServosRequest_(const ContainerAllocator& _alloc)
    : pos(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _pos_type;
  _pos_type pos;





  typedef boost::shared_ptr< ::rollout::MoveServosRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rollout::MoveServosRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveServosRequest_

typedef ::rollout::MoveServosRequest_<std::allocator<void> > MoveServosRequest;

typedef boost::shared_ptr< ::rollout::MoveServosRequest > MoveServosRequestPtr;
typedef boost::shared_ptr< ::rollout::MoveServosRequest const> MoveServosRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rollout::MoveServosRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rollout::MoveServosRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rollout::MoveServosRequest_<ContainerAllocator1> & lhs, const ::rollout::MoveServosRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pos == rhs.pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rollout::MoveServosRequest_<ContainerAllocator1> & lhs, const ::rollout::MoveServosRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rollout

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rollout::MoveServosRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rollout::MoveServosRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rollout::MoveServosRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rollout::MoveServosRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rollout::MoveServosRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rollout::MoveServosRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rollout::MoveServosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ddbdf76cbefd59cd9a914780fdf2963";
  }

  static const char* value(const ::rollout::MoveServosRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ddbdf76cbefd59cULL;
  static const uint64_t static_value2 = 0xd9a914780fdf2963ULL;
};

template<class ContainerAllocator>
struct DataType< ::rollout::MoveServosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rollout/MoveServosRequest";
  }

  static const char* value(const ::rollout::MoveServosRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rollout::MoveServosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] pos\n"
;
  }

  static const char* value(const ::rollout::MoveServosRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rollout::MoveServosRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveServosRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rollout::MoveServosRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rollout::MoveServosRequest_<ContainerAllocator>& v)
  {
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLOUT_MESSAGE_MOVESERVOSREQUEST_H
