// Generated by gencpp from file rollout/MoveServos.msg
// DO NOT EDIT!


#ifndef ROLLOUT_MESSAGE_MOVESERVOS_H
#define ROLLOUT_MESSAGE_MOVESERVOS_H

#include <ros/service_traits.h>


#include <rollout/MoveServosRequest.h>
#include <rollout/MoveServosResponse.h>


namespace rollout
{

struct MoveServos
{

typedef MoveServosRequest Request;
typedef MoveServosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveServos
} // namespace rollout


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rollout::MoveServos > {
  static const char* value()
  {
    return "183031e0becb89936a926d61b84a7478";
  }

  static const char* value(const ::rollout::MoveServos&) { return value(); }
};

template<>
struct DataType< ::rollout::MoveServos > {
  static const char* value()
  {
    return "rollout/MoveServos";
  }

  static const char* value(const ::rollout::MoveServos&) { return value(); }
};


// service_traits::MD5Sum< ::rollout::MoveServosRequest> should match
// service_traits::MD5Sum< ::rollout::MoveServos >
template<>
struct MD5Sum< ::rollout::MoveServosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rollout::MoveServos >::value();
  }
  static const char* value(const ::rollout::MoveServosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rollout::MoveServosRequest> should match
// service_traits::DataType< ::rollout::MoveServos >
template<>
struct DataType< ::rollout::MoveServosRequest>
{
  static const char* value()
  {
    return DataType< ::rollout::MoveServos >::value();
  }
  static const char* value(const ::rollout::MoveServosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rollout::MoveServosResponse> should match
// service_traits::MD5Sum< ::rollout::MoveServos >
template<>
struct MD5Sum< ::rollout::MoveServosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rollout::MoveServos >::value();
  }
  static const char* value(const ::rollout::MoveServosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rollout::MoveServosResponse> should match
// service_traits::DataType< ::rollout::MoveServos >
template<>
struct DataType< ::rollout::MoveServosResponse>
{
  static const char* value()
  {
    return DataType< ::rollout::MoveServos >::value();
  }
  static const char* value(const ::rollout::MoveServosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROLLOUT_MESSAGE_MOVESERVOS_H
