// Generated by gencpp from file rollout/rolloutReqRequest.msg
// DO NOT EDIT!


#ifndef ROLLOUT_MESSAGE_ROLLOUTREQREQUEST_H
#define ROLLOUT_MESSAGE_ROLLOUTREQREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rollout
{
template <class ContainerAllocator>
struct rolloutReqRequest_
{
  typedef rolloutReqRequest_<ContainerAllocator> Type;

  rolloutReqRequest_()
    : actions()  {
    }
  rolloutReqRequest_(const ContainerAllocator& _alloc)
    : actions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _actions_type;
  _actions_type actions;





  typedef boost::shared_ptr< ::rollout::rolloutReqRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rollout::rolloutReqRequest_<ContainerAllocator> const> ConstPtr;

}; // struct rolloutReqRequest_

typedef ::rollout::rolloutReqRequest_<std::allocator<void> > rolloutReqRequest;

typedef boost::shared_ptr< ::rollout::rolloutReqRequest > rolloutReqRequestPtr;
typedef boost::shared_ptr< ::rollout::rolloutReqRequest const> rolloutReqRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rollout::rolloutReqRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rollout::rolloutReqRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rollout::rolloutReqRequest_<ContainerAllocator1> & lhs, const ::rollout::rolloutReqRequest_<ContainerAllocator2> & rhs)
{
  return lhs.actions == rhs.actions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rollout::rolloutReqRequest_<ContainerAllocator1> & lhs, const ::rollout::rolloutReqRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rollout

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rollout::rolloutReqRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rollout::rolloutReqRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rollout::rolloutReqRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rollout::rolloutReqRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rollout::rolloutReqRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rollout::rolloutReqRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rollout::rolloutReqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb0eed2c2e2939ef752b1fa8fa9c2ab9";
  }

  static const char* value(const ::rollout::rolloutReqRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb0eed2c2e2939efULL;
  static const uint64_t static_value2 = 0x752b1fa8fa9c2ab9ULL;
};

template<class ContainerAllocator>
struct DataType< ::rollout::rolloutReqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rollout/rolloutReqRequest";
  }

  static const char* value(const ::rollout::rolloutReqRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rollout::rolloutReqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] actions\n"
;
  }

  static const char* value(const ::rollout::rolloutReqRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rollout::rolloutReqRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rolloutReqRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rollout::rolloutReqRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rollout::rolloutReqRequest_<ContainerAllocator>& v)
  {
    s << indent << "actions[]" << std::endl;
    for (size_t i = 0; i < v.actions.size(); ++i)
    {
      s << indent << "  actions[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.actions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLOUT_MESSAGE_ROLLOUTREQREQUEST_H
