// Generated by gencpp from file rollout/rolloutReqResponse.msg
// DO NOT EDIT!


#ifndef ROLLOUT_MESSAGE_ROLLOUTREQRESPONSE_H
#define ROLLOUT_MESSAGE_ROLLOUTREQRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rollout
{
template <class ContainerAllocator>
struct rolloutReqResponse_
{
  typedef rolloutReqResponse_<ContainerAllocator> Type;

  rolloutReqResponse_()
    : states()
    , actions()
    , time()
    , success(false)
    , reason()  {
    }
  rolloutReqResponse_(const ContainerAllocator& _alloc)
    : states(_alloc)
    , actions(_alloc)
    , time(_alloc)
    , success(false)
    , reason(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _states_type;
  _states_type states;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _actions_type;
  _actions_type actions;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _time_type;
  _time_type time;

   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reason_type;
  _reason_type reason;





  typedef boost::shared_ptr< ::rollout::rolloutReqResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rollout::rolloutReqResponse_<ContainerAllocator> const> ConstPtr;

}; // struct rolloutReqResponse_

typedef ::rollout::rolloutReqResponse_<std::allocator<void> > rolloutReqResponse;

typedef boost::shared_ptr< ::rollout::rolloutReqResponse > rolloutReqResponsePtr;
typedef boost::shared_ptr< ::rollout::rolloutReqResponse const> rolloutReqResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rollout::rolloutReqResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rollout::rolloutReqResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rollout::rolloutReqResponse_<ContainerAllocator1> & lhs, const ::rollout::rolloutReqResponse_<ContainerAllocator2> & rhs)
{
  return lhs.states == rhs.states &&
    lhs.actions == rhs.actions &&
    lhs.time == rhs.time &&
    lhs.success == rhs.success &&
    lhs.reason == rhs.reason;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rollout::rolloutReqResponse_<ContainerAllocator1> & lhs, const ::rollout::rolloutReqResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rollout

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rollout::rolloutReqResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rollout::rolloutReqResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rollout::rolloutReqResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rollout::rolloutReqResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rollout::rolloutReqResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rollout::rolloutReqResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rollout::rolloutReqResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5cebb4d45e8de7ba5ee164231614c7a0";
  }

  static const char* value(const ::rollout::rolloutReqResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5cebb4d45e8de7baULL;
  static const uint64_t static_value2 = 0x5ee164231614c7a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::rollout::rolloutReqResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rollout/rolloutReqResponse";
  }

  static const char* value(const ::rollout::rolloutReqResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rollout::rolloutReqResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] states\n"
"float32[] actions\n"
"float32[] time\n"
"bool success\n"
"string reason\n"
;
  }

  static const char* value(const ::rollout::rolloutReqResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rollout::rolloutReqResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.states);
      stream.next(m.actions);
      stream.next(m.time);
      stream.next(m.success);
      stream.next(m.reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rolloutReqResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rollout::rolloutReqResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rollout::rolloutReqResponse_<ContainerAllocator>& v)
  {
    s << indent << "states[]" << std::endl;
    for (size_t i = 0; i < v.states.size(); ++i)
    {
      s << indent << "  states[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.states[i]);
    }
    s << indent << "actions[]" << std::endl;
    for (size_t i = 0; i < v.actions.size(); ++i)
    {
      s << indent << "  actions[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.actions[i]);
    }
    s << indent << "time[]" << std::endl;
    for (size_t i = 0; i < v.time.size(); ++i)
    {
      s << indent << "  time[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.time[i]);
    }
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLOUT_MESSAGE_ROLLOUTREQRESPONSE_H
