// Generated by gencpp from file rollout/rolloutReqMod.msg
// DO NOT EDIT!


#ifndef ROLLOUT_MESSAGE_ROLLOUTREQMOD_H
#define ROLLOUT_MESSAGE_ROLLOUTREQMOD_H

#include <ros/service_traits.h>


#include <rollout/rolloutReqModRequest.h>
#include <rollout/rolloutReqModResponse.h>


namespace rollout
{

struct rolloutReqMod
{

typedef rolloutReqModRequest Request;
typedef rolloutReqModResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rolloutReqMod
} // namespace rollout


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rollout::rolloutReqMod > {
  static const char* value()
  {
    return "99038b95d1ebc1ede29fc60628f376a0";
  }

  static const char* value(const ::rollout::rolloutReqMod&) { return value(); }
};

template<>
struct DataType< ::rollout::rolloutReqMod > {
  static const char* value()
  {
    return "rollout/rolloutReqMod";
  }

  static const char* value(const ::rollout::rolloutReqMod&) { return value(); }
};


// service_traits::MD5Sum< ::rollout::rolloutReqModRequest> should match
// service_traits::MD5Sum< ::rollout::rolloutReqMod >
template<>
struct MD5Sum< ::rollout::rolloutReqModRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rollout::rolloutReqMod >::value();
  }
  static const char* value(const ::rollout::rolloutReqModRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rollout::rolloutReqModRequest> should match
// service_traits::DataType< ::rollout::rolloutReqMod >
template<>
struct DataType< ::rollout::rolloutReqModRequest>
{
  static const char* value()
  {
    return DataType< ::rollout::rolloutReqMod >::value();
  }
  static const char* value(const ::rollout::rolloutReqModRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rollout::rolloutReqModResponse> should match
// service_traits::MD5Sum< ::rollout::rolloutReqMod >
template<>
struct MD5Sum< ::rollout::rolloutReqModResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rollout::rolloutReqMod >::value();
  }
  static const char* value(const ::rollout::rolloutReqModResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rollout::rolloutReqModResponse> should match
// service_traits::DataType< ::rollout::rolloutReqMod >
template<>
struct DataType< ::rollout::rolloutReqModResponse>
{
  static const char* value()
  {
    return DataType< ::rollout::rolloutReqMod >::value();
  }
  static const char* value(const ::rollout::rolloutReqModResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROLLOUT_MESSAGE_ROLLOUTREQMOD_H
