// Generated by gencpp from file rollout/rolloutReqModRequest.msg
// DO NOT EDIT!


#ifndef ROLLOUT_MESSAGE_ROLLOUTREQMODREQUEST_H
#define ROLLOUT_MESSAGE_ROLLOUTREQMODREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rollout
{
template <class ContainerAllocator>
struct rolloutReqModRequest_
{
  typedef rolloutReqModRequest_<ContainerAllocator> Type;

  rolloutReqModRequest_()
    : actions()  {
    }
  rolloutReqModRequest_(const ContainerAllocator& _alloc)
    : actions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _actions_type;
  _actions_type actions;





  typedef boost::shared_ptr< ::rollout::rolloutReqModRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rollout::rolloutReqModRequest_<ContainerAllocator> const> ConstPtr;

}; // struct rolloutReqModRequest_

typedef ::rollout::rolloutReqModRequest_<std::allocator<void> > rolloutReqModRequest;

typedef boost::shared_ptr< ::rollout::rolloutReqModRequest > rolloutReqModRequestPtr;
typedef boost::shared_ptr< ::rollout::rolloutReqModRequest const> rolloutReqModRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rollout::rolloutReqModRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rollout::rolloutReqModRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rollout::rolloutReqModRequest_<ContainerAllocator1> & lhs, const ::rollout::rolloutReqModRequest_<ContainerAllocator2> & rhs)
{
  return lhs.actions == rhs.actions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rollout::rolloutReqModRequest_<ContainerAllocator1> & lhs, const ::rollout::rolloutReqModRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rollout

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rollout::rolloutReqModRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rollout::rolloutReqModRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rollout::rolloutReqModRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rollout::rolloutReqModRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rollout::rolloutReqModRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rollout::rolloutReqModRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rollout::rolloutReqModRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb0eed2c2e2939ef752b1fa8fa9c2ab9";
  }

  static const char* value(const ::rollout::rolloutReqModRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb0eed2c2e2939efULL;
  static const uint64_t static_value2 = 0x752b1fa8fa9c2ab9ULL;
};

template<class ContainerAllocator>
struct DataType< ::rollout::rolloutReqModRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rollout/rolloutReqModRequest";
  }

  static const char* value(const ::rollout::rolloutReqModRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rollout::rolloutReqModRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] actions\n"
;
  }

  static const char* value(const ::rollout::rolloutReqModRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rollout::rolloutReqModRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rolloutReqModRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rollout::rolloutReqModRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rollout::rolloutReqModRequest_<ContainerAllocator>& v)
  {
    s << indent << "actions[]" << std::endl;
    for (size_t i = 0; i < v.actions.size(); ++i)
    {
      s << indent << "  actions[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.actions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLOUT_MESSAGE_ROLLOUTREQMODREQUEST_H
