// Generated by gencpp from file rollout/rolloutReqFileRequest.msg
// DO NOT EDIT!


#ifndef ROLLOUT_MESSAGE_ROLLOUTREQFILEREQUEST_H
#define ROLLOUT_MESSAGE_ROLLOUTREQFILEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rollout
{
template <class ContainerAllocator>
struct rolloutReqFileRequest_
{
  typedef rolloutReqFileRequest_<ContainerAllocator> Type;

  rolloutReqFileRequest_()
    : file()  {
    }
  rolloutReqFileRequest_(const ContainerAllocator& _alloc)
    : file(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _file_type;
  _file_type file;





  typedef boost::shared_ptr< ::rollout::rolloutReqFileRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rollout::rolloutReqFileRequest_<ContainerAllocator> const> ConstPtr;

}; // struct rolloutReqFileRequest_

typedef ::rollout::rolloutReqFileRequest_<std::allocator<void> > rolloutReqFileRequest;

typedef boost::shared_ptr< ::rollout::rolloutReqFileRequest > rolloutReqFileRequestPtr;
typedef boost::shared_ptr< ::rollout::rolloutReqFileRequest const> rolloutReqFileRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rollout::rolloutReqFileRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rollout::rolloutReqFileRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rollout::rolloutReqFileRequest_<ContainerAllocator1> & lhs, const ::rollout::rolloutReqFileRequest_<ContainerAllocator2> & rhs)
{
  return lhs.file == rhs.file;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rollout::rolloutReqFileRequest_<ContainerAllocator1> & lhs, const ::rollout::rolloutReqFileRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rollout

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rollout::rolloutReqFileRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rollout::rolloutReqFileRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rollout::rolloutReqFileRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rollout::rolloutReqFileRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rollout::rolloutReqFileRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rollout::rolloutReqFileRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rollout::rolloutReqFileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e5aa404286053ca7f6cc32f23f37b85d";
  }

  static const char* value(const ::rollout::rolloutReqFileRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe5aa404286053ca7ULL;
  static const uint64_t static_value2 = 0xf6cc32f23f37b85dULL;
};

template<class ContainerAllocator>
struct DataType< ::rollout::rolloutReqFileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rollout/rolloutReqFileRequest";
  }

  static const char* value(const ::rollout::rolloutReqFileRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rollout::rolloutReqFileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string file\n"
;
  }

  static const char* value(const ::rollout::rolloutReqFileRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rollout::rolloutReqFileRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.file);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rolloutReqFileRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rollout::rolloutReqFileRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rollout::rolloutReqFileRequest_<ContainerAllocator>& v)
  {
    s << indent << "file: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.file);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLOUT_MESSAGE_ROLLOUTREQFILEREQUEST_H
