// Generated by gencpp from file rollout/rolloutReqFile.msg
// DO NOT EDIT!


#ifndef ROLLOUT_MESSAGE_ROLLOUTREQFILE_H
#define ROLLOUT_MESSAGE_ROLLOUTREQFILE_H

#include <ros/service_traits.h>


#include <rollout/rolloutReqFileRequest.h>
#include <rollout/rolloutReqFileResponse.h>


namespace rollout
{

struct rolloutReqFile
{

typedef rolloutReqFileRequest Request;
typedef rolloutReqFileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rolloutReqFile
} // namespace rollout


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rollout::rolloutReqFile > {
  static const char* value()
  {
    return "f682d82c4e2a8d10743450971038e4c0";
  }

  static const char* value(const ::rollout::rolloutReqFile&) { return value(); }
};

template<>
struct DataType< ::rollout::rolloutReqFile > {
  static const char* value()
  {
    return "rollout/rolloutReqFile";
  }

  static const char* value(const ::rollout::rolloutReqFile&) { return value(); }
};


// service_traits::MD5Sum< ::rollout::rolloutReqFileRequest> should match
// service_traits::MD5Sum< ::rollout::rolloutReqFile >
template<>
struct MD5Sum< ::rollout::rolloutReqFileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rollout::rolloutReqFile >::value();
  }
  static const char* value(const ::rollout::rolloutReqFileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rollout::rolloutReqFileRequest> should match
// service_traits::DataType< ::rollout::rolloutReqFile >
template<>
struct DataType< ::rollout::rolloutReqFileRequest>
{
  static const char* value()
  {
    return DataType< ::rollout::rolloutReqFile >::value();
  }
  static const char* value(const ::rollout::rolloutReqFileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rollout::rolloutReqFileResponse> should match
// service_traits::MD5Sum< ::rollout::rolloutReqFile >
template<>
struct MD5Sum< ::rollout::rolloutReqFileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rollout::rolloutReqFile >::value();
  }
  static const char* value(const ::rollout::rolloutReqFileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rollout::rolloutReqFileResponse> should match
// service_traits::DataType< ::rollout::rolloutReqFile >
template<>
struct DataType< ::rollout::rolloutReqFileResponse>
{
  static const char* value()
  {
    return DataType< ::rollout::rolloutReqFile >::value();
  }
  static const char* value(const ::rollout::rolloutReqFileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROLLOUT_MESSAGE_ROLLOUTREQFILE_H
