// Generated by gencpp from file rollout/TargetAngles.msg
// DO NOT EDIT!


#ifndef ROLLOUT_MESSAGE_TARGETANGLES_H
#define ROLLOUT_MESSAGE_TARGETANGLES_H

#include <ros/service_traits.h>


#include <rollout/TargetAnglesRequest.h>
#include <rollout/TargetAnglesResponse.h>


namespace rollout
{

struct TargetAngles
{

typedef TargetAnglesRequest Request;
typedef TargetAnglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TargetAngles
} // namespace rollout


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rollout::TargetAngles > {
  static const char* value()
  {
    return "370f9a53bb9fc4e03100f718ee81318b";
  }

  static const char* value(const ::rollout::TargetAngles&) { return value(); }
};

template<>
struct DataType< ::rollout::TargetAngles > {
  static const char* value()
  {
    return "rollout/TargetAngles";
  }

  static const char* value(const ::rollout::TargetAngles&) { return value(); }
};


// service_traits::MD5Sum< ::rollout::TargetAnglesRequest> should match
// service_traits::MD5Sum< ::rollout::TargetAngles >
template<>
struct MD5Sum< ::rollout::TargetAnglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rollout::TargetAngles >::value();
  }
  static const char* value(const ::rollout::TargetAnglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rollout::TargetAnglesRequest> should match
// service_traits::DataType< ::rollout::TargetAngles >
template<>
struct DataType< ::rollout::TargetAnglesRequest>
{
  static const char* value()
  {
    return DataType< ::rollout::TargetAngles >::value();
  }
  static const char* value(const ::rollout::TargetAnglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rollout::TargetAnglesResponse> should match
// service_traits::MD5Sum< ::rollout::TargetAngles >
template<>
struct MD5Sum< ::rollout::TargetAnglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rollout::TargetAngles >::value();
  }
  static const char* value(const ::rollout::TargetAnglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rollout::TargetAnglesResponse> should match
// service_traits::DataType< ::rollout::TargetAngles >
template<>
struct DataType< ::rollout::TargetAnglesResponse>
{
  static const char* value()
  {
    return DataType< ::rollout::TargetAngles >::value();
  }
  static const char* value(const ::rollout::TargetAnglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROLLOUT_MESSAGE_TARGETANGLES_H
