// Generated by gencpp from file rollout/TargetAnglesResponse.msg
// DO NOT EDIT!


#ifndef ROLLOUT_MESSAGE_TARGETANGLESRESPONSE_H
#define ROLLOUT_MESSAGE_TARGETANGLESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rollout
{
template <class ContainerAllocator>
struct TargetAnglesResponse_
{
  typedef TargetAnglesResponse_<ContainerAllocator> Type;

  TargetAnglesResponse_()
    : success(false)  {
    }
  TargetAnglesResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::rollout::TargetAnglesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rollout::TargetAnglesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TargetAnglesResponse_

typedef ::rollout::TargetAnglesResponse_<std::allocator<void> > TargetAnglesResponse;

typedef boost::shared_ptr< ::rollout::TargetAnglesResponse > TargetAnglesResponsePtr;
typedef boost::shared_ptr< ::rollout::TargetAnglesResponse const> TargetAnglesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rollout::TargetAnglesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rollout::TargetAnglesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rollout::TargetAnglesResponse_<ContainerAllocator1> & lhs, const ::rollout::TargetAnglesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rollout::TargetAnglesResponse_<ContainerAllocator1> & lhs, const ::rollout::TargetAnglesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rollout

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rollout::TargetAnglesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rollout::TargetAnglesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rollout::TargetAnglesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rollout::TargetAnglesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rollout::TargetAnglesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rollout::TargetAnglesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rollout::TargetAnglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::rollout::TargetAnglesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::rollout::TargetAnglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rollout/TargetAnglesResponse";
  }

  static const char* value(const ::rollout::TargetAnglesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rollout::TargetAnglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::rollout::TargetAnglesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rollout::TargetAnglesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetAnglesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rollout::TargetAnglesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rollout::TargetAnglesResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLOUT_MESSAGE_TARGETANGLESRESPONSE_H
