// Generated by gencpp from file hand_control/close.msg
// DO NOT EDIT!


#ifndef HAND_CONTROL_MESSAGE_CLOSE_H
#define HAND_CONTROL_MESSAGE_CLOSE_H

#include <ros/service_traits.h>


#include <hand_control/closeRequest.h>
#include <hand_control/closeResponse.h>


namespace hand_control
{

struct close
{

typedef closeRequest Request;
typedef closeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct close
} // namespace hand_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hand_control::close > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::hand_control::close&) { return value(); }
};

template<>
struct DataType< ::hand_control::close > {
  static const char* value()
  {
    return "hand_control/close";
  }

  static const char* value(const ::hand_control::close&) { return value(); }
};


// service_traits::MD5Sum< ::hand_control::closeRequest> should match
// service_traits::MD5Sum< ::hand_control::close >
template<>
struct MD5Sum< ::hand_control::closeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hand_control::close >::value();
  }
  static const char* value(const ::hand_control::closeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_control::closeRequest> should match
// service_traits::DataType< ::hand_control::close >
template<>
struct DataType< ::hand_control::closeRequest>
{
  static const char* value()
  {
    return DataType< ::hand_control::close >::value();
  }
  static const char* value(const ::hand_control::closeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hand_control::closeResponse> should match
// service_traits::MD5Sum< ::hand_control::close >
template<>
struct MD5Sum< ::hand_control::closeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hand_control::close >::value();
  }
  static const char* value(const ::hand_control::closeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_control::closeResponse> should match
// service_traits::DataType< ::hand_control::close >
template<>
struct DataType< ::hand_control::closeResponse>
{
  static const char* value()
  {
    return DataType< ::hand_control::close >::value();
  }
  static const char* value(const ::hand_control::closeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAND_CONTROL_MESSAGE_CLOSE_H
