// Generated by gencpp from file hand_control/IsDropped.msg
// DO NOT EDIT!


#ifndef HAND_CONTROL_MESSAGE_ISDROPPED_H
#define HAND_CONTROL_MESSAGE_ISDROPPED_H

#include <ros/service_traits.h>


#include <hand_control/IsDroppedRequest.h>
#include <hand_control/IsDroppedResponse.h>


namespace hand_control
{

struct IsDropped
{

typedef IsDroppedRequest Request;
typedef IsDroppedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IsDropped
} // namespace hand_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hand_control::IsDropped > {
  static const char* value()
  {
    return "89b1ea20d43c8bbdf4c72f92a40ab2ad";
  }

  static const char* value(const ::hand_control::IsDropped&) { return value(); }
};

template<>
struct DataType< ::hand_control::IsDropped > {
  static const char* value()
  {
    return "hand_control/IsDropped";
  }

  static const char* value(const ::hand_control::IsDropped&) { return value(); }
};


// service_traits::MD5Sum< ::hand_control::IsDroppedRequest> should match
// service_traits::MD5Sum< ::hand_control::IsDropped >
template<>
struct MD5Sum< ::hand_control::IsDroppedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hand_control::IsDropped >::value();
  }
  static const char* value(const ::hand_control::IsDroppedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_control::IsDroppedRequest> should match
// service_traits::DataType< ::hand_control::IsDropped >
template<>
struct DataType< ::hand_control::IsDroppedRequest>
{
  static const char* value()
  {
    return DataType< ::hand_control::IsDropped >::value();
  }
  static const char* value(const ::hand_control::IsDroppedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hand_control::IsDroppedResponse> should match
// service_traits::MD5Sum< ::hand_control::IsDropped >
template<>
struct MD5Sum< ::hand_control::IsDroppedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hand_control::IsDropped >::value();
  }
  static const char* value(const ::hand_control::IsDroppedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_control::IsDroppedResponse> should match
// service_traits::DataType< ::hand_control::IsDropped >
template<>
struct DataType< ::hand_control::IsDroppedResponse>
{
  static const char* value()
  {
    return DataType< ::hand_control::IsDropped >::value();
  }
  static const char* value(const ::hand_control::IsDroppedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAND_CONTROL_MESSAGE_ISDROPPED_H
