// Generated by gencpp from file hand_control/net_evalResponse.msg
// DO NOT EDIT!


#ifndef HAND_CONTROL_MESSAGE_NET_EVALRESPONSE_H
#define HAND_CONTROL_MESSAGE_NET_EVALRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hand_control
{
template <class ContainerAllocator>
struct net_evalResponse_
{
  typedef net_evalResponse_<ContainerAllocator> Type;

  net_evalResponse_()
    : action()  {
    }
  net_evalResponse_(const ContainerAllocator& _alloc)
    : action(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::hand_control::net_evalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_control::net_evalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct net_evalResponse_

typedef ::hand_control::net_evalResponse_<std::allocator<void> > net_evalResponse;

typedef boost::shared_ptr< ::hand_control::net_evalResponse > net_evalResponsePtr;
typedef boost::shared_ptr< ::hand_control::net_evalResponse const> net_evalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_control::net_evalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_control::net_evalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hand_control::net_evalResponse_<ContainerAllocator1> & lhs, const ::hand_control::net_evalResponse_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hand_control::net_evalResponse_<ContainerAllocator1> & lhs, const ::hand_control::net_evalResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hand_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hand_control::net_evalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_control::net_evalResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_control::net_evalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_control::net_evalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_control::net_evalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_control::net_evalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_control::net_evalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a70a7d92e0376dcb967914076f276ea6";
  }

  static const char* value(const ::hand_control::net_evalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa70a7d92e0376dcbULL;
  static const uint64_t static_value2 = 0x967914076f276ea6ULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_control::net_evalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_control/net_evalResponse";
  }

  static const char* value(const ::hand_control::net_evalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_control::net_evalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] action\n"
;
  }

  static const char* value(const ::hand_control::net_evalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_control::net_evalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct net_evalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_control::net_evalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_control::net_evalResponse_<ContainerAllocator>& v)
  {
    s << indent << "action[]" << std::endl;
    for (size_t i = 0; i < v.action.size(); ++i)
    {
      s << indent << "  action[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.action[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_CONTROL_MESSAGE_NET_EVALRESPONSE_H
