// Generated by gencpp from file hand_control/RegraspObject.msg
// DO NOT EDIT!


#ifndef HAND_CONTROL_MESSAGE_REGRASPOBJECT_H
#define HAND_CONTROL_MESSAGE_REGRASPOBJECT_H

#include <ros/service_traits.h>


#include <hand_control/RegraspObjectRequest.h>
#include <hand_control/RegraspObjectResponse.h>


namespace hand_control
{

struct RegraspObject
{

typedef RegraspObjectRequest Request;
typedef RegraspObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RegraspObject
} // namespace hand_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hand_control::RegraspObject > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::hand_control::RegraspObject&) { return value(); }
};

template<>
struct DataType< ::hand_control::RegraspObject > {
  static const char* value()
  {
    return "hand_control/RegraspObject";
  }

  static const char* value(const ::hand_control::RegraspObject&) { return value(); }
};


// service_traits::MD5Sum< ::hand_control::RegraspObjectRequest> should match
// service_traits::MD5Sum< ::hand_control::RegraspObject >
template<>
struct MD5Sum< ::hand_control::RegraspObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hand_control::RegraspObject >::value();
  }
  static const char* value(const ::hand_control::RegraspObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_control::RegraspObjectRequest> should match
// service_traits::DataType< ::hand_control::RegraspObject >
template<>
struct DataType< ::hand_control::RegraspObjectRequest>
{
  static const char* value()
  {
    return DataType< ::hand_control::RegraspObject >::value();
  }
  static const char* value(const ::hand_control::RegraspObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hand_control::RegraspObjectResponse> should match
// service_traits::MD5Sum< ::hand_control::RegraspObject >
template<>
struct MD5Sum< ::hand_control::RegraspObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hand_control::RegraspObject >::value();
  }
  static const char* value(const ::hand_control::RegraspObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_control::RegraspObjectResponse> should match
// service_traits::DataType< ::hand_control::RegraspObject >
template<>
struct DataType< ::hand_control::RegraspObjectResponse>
{
  static const char* value()
  {
    return DataType< ::hand_control::RegraspObject >::value();
  }
  static const char* value(const ::hand_control::RegraspObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAND_CONTROL_MESSAGE_REGRASPOBJECT_H
