// Generated by gencpp from file hand_control/TargetPos.msg
// DO NOT EDIT!


#ifndef HAND_CONTROL_MESSAGE_TARGETPOS_H
#define HAND_CONTROL_MESSAGE_TARGETPOS_H

#include <ros/service_traits.h>


#include <hand_control/TargetPosRequest.h>
#include <hand_control/TargetPosResponse.h>


namespace hand_control
{

struct TargetPos
{

typedef TargetPosRequest Request;
typedef TargetPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TargetPos
} // namespace hand_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hand_control::TargetPos > {
  static const char* value()
  {
    return "e227be5dbe0ddab6b23e84a527804c51";
  }

  static const char* value(const ::hand_control::TargetPos&) { return value(); }
};

template<>
struct DataType< ::hand_control::TargetPos > {
  static const char* value()
  {
    return "hand_control/TargetPos";
  }

  static const char* value(const ::hand_control::TargetPos&) { return value(); }
};


// service_traits::MD5Sum< ::hand_control::TargetPosRequest> should match
// service_traits::MD5Sum< ::hand_control::TargetPos >
template<>
struct MD5Sum< ::hand_control::TargetPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hand_control::TargetPos >::value();
  }
  static const char* value(const ::hand_control::TargetPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_control::TargetPosRequest> should match
// service_traits::DataType< ::hand_control::TargetPos >
template<>
struct DataType< ::hand_control::TargetPosRequest>
{
  static const char* value()
  {
    return DataType< ::hand_control::TargetPos >::value();
  }
  static const char* value(const ::hand_control::TargetPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hand_control::TargetPosResponse> should match
// service_traits::MD5Sum< ::hand_control::TargetPos >
template<>
struct MD5Sum< ::hand_control::TargetPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hand_control::TargetPos >::value();
  }
  static const char* value(const ::hand_control::TargetPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_control::TargetPosResponse> should match
// service_traits::DataType< ::hand_control::TargetPos >
template<>
struct DataType< ::hand_control::TargetPosResponse>
{
  static const char* value()
  {
    return DataType< ::hand_control::TargetPos >::value();
  }
  static const char* value(const ::hand_control::TargetPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAND_CONTROL_MESSAGE_TARGETPOS_H
