// Generated by gencpp from file hand_control/TargetPosResponse.msg
// DO NOT EDIT!


#ifndef HAND_CONTROL_MESSAGE_TARGETPOSRESPONSE_H
#define HAND_CONTROL_MESSAGE_TARGETPOSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hand_control
{
template <class ContainerAllocator>
struct TargetPosResponse_
{
  typedef TargetPosResponse_<ContainerAllocator> Type;

  TargetPosResponse_()
    : angle()  {
    }
  TargetPosResponse_(const ContainerAllocator& _alloc)
    : angle(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::hand_control::TargetPosResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_control::TargetPosResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TargetPosResponse_

typedef ::hand_control::TargetPosResponse_<std::allocator<void> > TargetPosResponse;

typedef boost::shared_ptr< ::hand_control::TargetPosResponse > TargetPosResponsePtr;
typedef boost::shared_ptr< ::hand_control::TargetPosResponse const> TargetPosResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_control::TargetPosResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_control::TargetPosResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hand_control::TargetPosResponse_<ContainerAllocator1> & lhs, const ::hand_control::TargetPosResponse_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hand_control::TargetPosResponse_<ContainerAllocator1> & lhs, const ::hand_control::TargetPosResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hand_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hand_control::TargetPosResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_control::TargetPosResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_control::TargetPosResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_control::TargetPosResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_control::TargetPosResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_control::TargetPosResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_control::TargetPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e227be5dbe0ddab6b23e84a527804c51";
  }

  static const char* value(const ::hand_control::TargetPosResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe227be5dbe0ddab6ULL;
  static const uint64_t static_value2 = 0xb23e84a527804c51ULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_control::TargetPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_control/TargetPosResponse";
  }

  static const char* value(const ::hand_control::TargetPosResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_control::TargetPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] angle\n"
;
  }

  static const char* value(const ::hand_control::TargetPosResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_control::TargetPosResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetPosResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_control::TargetPosResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_control::TargetPosResponse_<ContainerAllocator>& v)
  {
    s << indent << "angle[]" << std::endl;
    for (size_t i = 0; i < v.angle.size(); ++i)
    {
      s << indent << "  angle[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.angle[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_CONTROL_MESSAGE_TARGETPOSRESPONSE_H
