// Generated by gencpp from file hand_control/TargetAnglesRequest.msg
// DO NOT EDIT!


#ifndef HAND_CONTROL_MESSAGE_TARGETANGLESREQUEST_H
#define HAND_CONTROL_MESSAGE_TARGETANGLESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hand_control
{
template <class ContainerAllocator>
struct TargetAnglesRequest_
{
  typedef TargetAnglesRequest_<ContainerAllocator> Type;

  TargetAnglesRequest_()
    : angles()  {
    }
  TargetAnglesRequest_(const ContainerAllocator& _alloc)
    : angles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _angles_type;
  _angles_type angles;





  typedef boost::shared_ptr< ::hand_control::TargetAnglesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_control::TargetAnglesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TargetAnglesRequest_

typedef ::hand_control::TargetAnglesRequest_<std::allocator<void> > TargetAnglesRequest;

typedef boost::shared_ptr< ::hand_control::TargetAnglesRequest > TargetAnglesRequestPtr;
typedef boost::shared_ptr< ::hand_control::TargetAnglesRequest const> TargetAnglesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_control::TargetAnglesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_control::TargetAnglesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hand_control::TargetAnglesRequest_<ContainerAllocator1> & lhs, const ::hand_control::TargetAnglesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angles == rhs.angles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hand_control::TargetAnglesRequest_<ContainerAllocator1> & lhs, const ::hand_control::TargetAnglesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hand_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hand_control::TargetAnglesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_control::TargetAnglesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_control::TargetAnglesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_control::TargetAnglesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_control::TargetAnglesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_control::TargetAnglesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_control::TargetAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "900e68ab26db7b254c95cc40be37fb5c";
  }

  static const char* value(const ::hand_control::TargetAnglesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x900e68ab26db7b25ULL;
  static const uint64_t static_value2 = 0x4c95cc40be37fb5cULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_control::TargetAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_control/TargetAnglesRequest";
  }

  static const char* value(const ::hand_control::TargetAnglesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_control::TargetAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] angles\n"
;
  }

  static const char* value(const ::hand_control::TargetAnglesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_control::TargetAnglesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetAnglesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_control::TargetAnglesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_control::TargetAnglesRequest_<ContainerAllocator>& v)
  {
    s << indent << "angles[]" << std::endl;
    for (size_t i = 0; i < v.angles.size(); ++i)
    {
      s << indent << "  angles[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.angles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_CONTROL_MESSAGE_TARGETANGLESREQUEST_H
